### ISSUE TITLE
Multi-account login

### ISSUE THREAD

**Issue by container1** [MozillaSocial/mozilla-social-android#476] opened 2024-04-20 04:44 UTC
Multi-account login not yet given?!
...is it a planned feature for later?
And sorry, but are there no App settings?
PS: same for Mozilla Social
Thx

**Comment by cadeyrn** [comment] 2024-04-20 05:40
Multi account support is #351.
You can find the settings button on your profile tab.

**Comment by container1** [comment] 2024-04-20 05:50
Unfortunately seems like misunderstanding.
Seems implementation only given for multi account for single Instance but not single account for multi Instances?!
From my perspective, "Multi-Account login" suggest ability using Multiple Accounts, Istance independent.

**Comment by cadeyrn** [comment] 2024-04-20 06:30
Well, your only information was "Multi-account login" and the other issue is about "multi account support". That's pretty much the same. If you think it's about something different, that just shows how unclear your request is (there is no description at all, only the term "Multi-account login", nothing else!). Perhaps you should formulate your request more precisely in the original comment. 😉

**Comment by container1** [comment] 2024-04-20 06:41
Was not a request, more a question. 😉
It's related to Firefly (https://github.com/Firefly-Social/Firefly?tab=readme-ov-file#features-roadmap), where it's stated and forked from here. (...where I also asked)😉

**Comment by JohnOberhauser** [comment] 2024-04-20 21:46
Multi-account login is in the backlog.  I'll get to it at some point!  I'm going to close this issue since it's a duplicate of https://github.com/MozillaSocial/mozilla-social-android/issues/351

**Closed by JohnOberhauser** 2024-04-20 21:46 UTC
